const quotes = [
  "Believe you can and you're halfway there.",
  "The only way to do great work is to love what you do.",
  "Success is the sum of small efforts repeated every day.",
  "Dream big and dare to fail.",
  "Don't watch the clock; do what it does. Keep going.",
  "The future depends on what you do today.",
  "It always seems impossible until it's done.",
  "Believe in yourself and all that you are.",
  "Great things never come from comfort zones.",
  "Every day is a new beginning.",
  "Stay hungry, stay foolish.",
  "Your only limit is your mind.",
  "Difficult roads often lead to beautiful destinations.",
  "Action is the foundational key to all success.",
  "Don't stop until you're proud.",
  "Small steps every day lead to big results.",
  "Make today so awesome yesterday gets jealous.",
  "You are capable of more than you know.",
  "Focus on progress, not perfection.",
  "Turn your dreams into plans.",
  "The secret of getting ahead is getting started.",
  "Success begins with self-discipline.",
  "Be stronger than your excuses.",
  "One day or day one. You decide.",
  "Work hard in silence; let success make the noise.",
  "What you do today can improve all your tomorrows.",
  "Push yourself because no one else is going to do it for you.",
  "Don't be afraid to start over.",
  "Consistency beats intensity.",
  "Your future self will thank you.",
  "Stay positive, work hard, make it happen.",
  "Fall seven times, stand up eight.",
  "Nothing worth having comes easy.",
  "Doubt kills more dreams than failure ever will.",
  "Start where you are. Use what you have. Do what you can.",
  "Success doesn't come from what you do occasionally.",
  "Keep going; you're closer than you think.",
  "Learn from yesterday, live for today, hope for tomorrow.",
  "The harder you work, the luckier you get.",
  "Don't let fear decide your future.",
  "You don't have to be perfect to make progress.",
  "Every accomplishment starts with the decision to try.",
  "Be the reason you believe in yourself.",
  "Great things take time.",
  "Do something today your future self will be proud of.",
  "Your attitude determines your direction.",
  "Success is a journey, not a destination.",
  "Keep your eyes on the goal.",
  "Make your own opportunities.",
  "Turn obstacles into opportunities.",
  "Your potential is endless.",
  "Never let failure define you.",
  "Choose courage over comfort.",
  "Discipline is choosing between what you want now and what you want most.",
  "The best time to start was yesterday. The next best time is now.",
  "Don't limit your challenges. Challenge your limits.",
  "A little progress each day adds up to big results.",
  "You can do hard things.",
  "Keep moving forward.",
  "Your dreams are worth the effort.",
  "Success starts with showing up.",
  "Be patient with yourself.",
  "Every expert was once a beginner.",
  "Mistakes are proof that you are trying.",
  "Don't compare your beginning to someone else's middle.",
  "Make it happen.",
  "Stay focused and never give up.",
  "Your effort matters.",
  "The best view comes after the hardest climb.",
  "Create the life you want to live.",
  "You are stronger than your setbacks.",
  "Keep learning, keep growing.",
  "Do it with passion or not at all.",
  "Hard work beats talent when talent doesn't work hard.",
  "Nothing changes if nothing changes.",
  "Be consistent even when nobody is watching.",
  "Your mindset shapes your reality.",
  "Every step forward counts.",
  "Don't wait for opportunity. Create it.",
  "Progress begins outside your comfort zone.",
  "You have the power to change your story.",
  "Stay committed to your goals.",
  "Success requires patience and persistence.",
  "Don't quit on a bad day.",
  "Believe in the process.",
  "Your journey is your own.",
  "Keep chasing your goals.",
  "Turn your pain into power.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "The beginning is always today.",
  "You are one decision away from a different life.",
  "Do what scares you until it doesn't.",
  "Make yourself proud.",
  "Your future is created by what you do today.",
  "Keep showing up.",
  "Dream it. Plan it. Do it.",
  "You were made to do great things.",
  "Never stop becoming better.",
  "The best is yet to come."
];

const button = document.querySelector("button");
const quote = document.querySelector("h1");
button.addEventListener('click', ()=>{
    const idx = Math.floor(Math.random()*quotes.length);
    quote.textContent = quotes[idx];
})